/**
 * Auto-generated wrapper header for confinement and interaction modules.
 * Sets MPI_ON if mpicc is used.
 * Generated by /home/thomas/workspace_thomas/entropic_particle_splitter/src/../python_tools/dtool_create_header_makefile.py
 */

#include "int_lennardjones.h"
#include "conf_splitter.h"
