# Simulation Parameters
F = 20.0
parts_per_set = 1
N = 1000
patience = 20
stepnumb = 50000
accur = 0.01
initwidth = 1.0
init_max_xpos = 0.7
max_steps_rec_trajects = 50000
skip_steps_rec_trajects = 50
max_numb_rec_trajects = 1

